ALTER TABLE public.storage_files 
ADD COLUMN IF NOT EXISTS width INT,
ADD COLUMN IF NOT EXISTS height INT,
ADD COLUMN IF NOT EXISTS original_size BIGINT,
ADD COLUMN IF NOT EXISTS optimized_size BIGINT,
ADD COLUMN IF NOT EXISTS compression_ratio NUMERIC(5,2),
ADD COLUMN IF NOT EXISTS mime_type VARCHAR(50);
